FROM registry.access.redhat.com/ubi8/ubi:latest

RUN dnf -y install httpd && \
    mkdir -m 775 -p /var/www/html/{install,ignition,artifacts}
COPY ./index.html /var/www/html

USER 1002
#EXPOSE 8080/tcp 8443/tcp


