FROM registry.access.redhat.com/ubi8/ubi:latest

ENV OCPVERSION="4.6.1"

ENV OCPRHCOSVERSION="4.6.1"

ENV HELPERPODVERSION="2.4.6.0"

ENV HELPERPOD_HTTP_PORT="8080"

ENV HELMVERSION="3.4.0"

#RUN dnf -y install httpd jq wget python38-pip && \
#    pip3 install ansible && \
#    mkdir -m 775 -p /var/www/html/{install,ignition,artifacts}

#COPY files/httpd.conf.j2 /usr/local/src/
#COPY scripts/startup.sh /usr/local/bin/
#COPY scripts/simpleEcho.sh /usr/local/bin/

RUN dnf -y install httpd jq wget
COPY ./index.html /var/www/html/.

USER 1002
EXPOSE 8080/tcp 8443/tcp


